# Generated by Django 4.2.4 on 2023-08-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_workeruser_email_alter_workeruser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workeruser',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
