# Generated by Django 4.2.4 on 2023-08-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_workeruser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workeruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='workeruser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
