# Generated by Django 4.2.4 on 2023-08-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_workeruser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workeruser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='workeruser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
