# Generated by Django 4.2.4 on 2023-08-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='reason',
            field=models.TextField(max_length=300),
        ),
    ]
