# Generated by Django 4.2.4 on 2023-08-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_leaveapplication_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('SICK_LEAVE', 'Sick Leave'), ('PAID_LEAVE', 'Paid Leave'), ('UNPAID_LEAVE', 'Unpaid Leave')], default='UNPAID_LEAVE', max_length=30),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined')], default='PENDING', max_length=30),
        ),
    ]
