# Generated by Django 4.2.4 on 2023-08-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_name_project_project_name_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_category', models.CharField(max_length=30)),
            ],
        ),
    ]
