# Generated by Django 4.2.4 on 2023-08-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_taskcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='task_category',
            field=models.CharField(choices=[('METERS', 'Meters'), ('NUMBER', 'Number')], max_length=30),
        ),
    ]
