# Generated by Django 4.2.4 on 2023-08-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_taskcategory_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='unit',
            field=models.CharField(choices=[('METERS', 'Meters'), ('QUANTITY', 'Quantity')], max_length=100),
        ),
    ]
