# Generated by Django 4.2.4 on 2023-08-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_taskcategory_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.taskcategory'),
        ),
    ]
