# Generated by Django 4.2.4 on 2023-08-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_rename_task_category_taskcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(default='1999-12-27'),
            preserve_default=False,
        ),
    ]
