# Generated by Django 4.2.4 on 2023-08-16 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
