# Generated by Django 4.2.4 on 2023-08-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_remove_task_progress_task_work_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
