# Generated by Django 4.2.4 on 2023-08-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_alter_project_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
    ]
