# Generated by Django 4.2.4 on 2023-08-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_alter_task_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
