# Generated by Django 4.2.4 on 2023-08-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_client_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
