# Generated by Django 4.2.4 on 2023-08-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='action',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='item',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
